function(set_compile_options target_name)
    string(TOLOWER ${CMAKE_BUILD_TYPE} build_type)

    if (${build_type} STREQUAL release)
        if (MSVC)
            target_compile_options(${target_name} PRIVATE /W4 /O2)
        else()
            target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic -O2)
        endif()
    elseif(${build_type} STREQUAL debug)
        if (MSVC)
            target_compile_options(${target_name} PRIVATE /W4 /DEBUG:FULL)
        else()
            target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic -g2)
        endif()
    endif()

    target_compile_definitions(${target_name} PRIVATE _CRT_SECURE_NO_WARNINGS)
endfunction()
